version: '3.8'

services:
  visualizerApp:
    image: dockersamples/visualizer:stable
    ports:
      - "8087:8080"
    deploy: 
      replicas: 1
      placement:
        constraints:
          - node.role == manager 
      restart_policy:
        condition: on-failure 
    networks:
      - visualizer_net  
      
networks:
  visualizer_net:
    driver: overlay 
